spring:
  application:
    name: notification-api-service

  mongodb:
    uri: mongodb://root:root@localhost:27017/notification-service?authSource=admin&uuidRepresentation=standard

  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: localhost:9092

kafka:
  ingest:
    topic: notification.ingest
  audit:
    topic: notification.audit

# Custom properties to manage which beans get loaded
messaging:
  providers:
    kafka:
      enabled: true
    aws:
      enabled: false
  fallback:
    rabbitmq:
      enabled: false
    mqtt:
      enabled: false
